export const GET_PRODUCTS = "GET_PRODUCTS";
export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_A_PRODUCT = "ADD_A_PRODUCT";
export const DELETE_A_PRODUCT = "DELETE_A_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const DELETE_A_CART_PRODUCT = "DELETE_A_CART_PRODUCT";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const PRODUCT_DESCRIPTION_SUCCESS = "PRODUCT_DESCRIPTION_SUCCESS";
export const FETCH_THE_PRODUCT = "FETCH_THE_PRODUCT";

export const ERROR_ACTION = "ERROR_ACTION";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
